apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-cluster-deploy
spec:
  selector:
    matchLabels:
      app: myapp-cluster-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-cluster-deploy
    spec:
      containers:
      - name: myapp-cluster-deploy
        image: dangtong/nodeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster-service
spec:
  selector:
    app: myapp-cluster-service
  ports:
  - port: 8080
    targetPort: 8080
