# bitnami/apache 이미지로 Pod 를 만들고 tier=FronEnd, app=apache 라벨 정보를 포함하세요
# Pod 정보를 출력 할때 라벨을 함께 출력 하세요
# app=apache 라벨을 가진 Pod 만 조회 하세요
# 만들어진 Pod에 env=dev 라는 라벨 정보를 추가 하세요
# created_by=kevin 이라는 Annotation을 추가 하세요
# apache Pod를 삭제 하세요

apiVersion: v1
kind: Pod
metadata:
  name: goapp-pod
  labels:
    name: goapp
    tier: FrontEnd
    app: apache
spec:
  containers:
  - name: goapp-container
    image: bitnami/apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
