# apiVersion: v1
# kind: Namespace
# metadata:
#   name: my-dev


apiVersion: v1
kind: Pod
metadata:
  name: my-dev-pod
  namespace: my-dev
  labels:
    name: my-dev
spec:
  containers:
  - name: my-dev-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
